Add uClibc patch for missing C99 float/ld wrappers
Without this patch Node v6.x will fail to compile due to the error:
`undefined reference to 'nearbyintf'`

The original patch can be found here:
https://git.uclibc.org/uClibc/commit/?id=6c4538905e65ceb203f59aaa9a61728e81c6bc0a

There were some lines that needed to be removed in order for the patch
to successfully apply on OpenWRT.